INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (2,1);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (3,18);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (4,3);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (5,4);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (8,28);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (14,5);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (23,12);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (24,10);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (25,10);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (26,10);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (27,10);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (28,19);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (28,31);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (28,32);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (30,8);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (32,3);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (34,12);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (34,13);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (34,14);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (34,20);
INSERT INTO Film_Acteur(FILMS_ID, ACTEURS_ID) VALUES (34,28);



